// Get two values from the user ‘password’ and ‘confirm password’  using the prompt box and display a message “Password validated” if both the values match else display the message “Password do not match”


var one=prompt('password');
var two=prompt('confirm password');// Style: line-space after the decalaration block
if (one===two){
   alert('Password validated');
}
else{ // Style: else can be moved to the line before
   alert('password do not match');
}


// Find the output of the following
// Logical AND operation
// true  && true; - true
// true  && false; - false
// false && true; - false
// false && false; - false

// Logical OR operation
// true  || true; - true
// true  || false; - true
// false || true; - true
// false || false; - false

// "foo" && "bar"; - "bar"
// "bar" && "foo"; - "foo"
// "foo" && ""; - ""
// ""    && "foo"; "foo"

// "foo" || "bar"; "foo"
// "bar" || "foo"; "bar"
// "foo" || ""; "foo"
// ""    || "foo"; "foo"



// Output of this alert( alert(1) || 2 || alert(3) );
//1 2


// Create a function which takes two input and (a,b) and display the sum, sub, multiplication, devision of those two numbers.

function input(a,b){
  var multiply = a*b //Style: semicolon missing
  alert (`${multiply}`);
}
//input(2,3);


// Function to display a number if user enters negative number
var num = prompt ("enter number");
checkNum(num);// Style: line space missing after the declaration block
function checkNum(num){
  if (num<0){
      alert ('Negative');
  }
  else{ // Style: else can be moved to line before 
      alert('positive');
  }
}



// If we list all the natural numbers below 10 that are multiples of 3 or 5, we get 3, 5, 6 and 9. The sum of these multiples is 23.
// Find the sum of all the multiples of 3 or 5 below 1000.




// If user enters positive number, that number won't be displayed



// Funnction to check whether an integer entered by the user is odd or even



// Funnction to take two input and show the relation using =, > or < i.e (21,45) 21 < 45, (23,12) 23 > 12



// Funnction to Check Whether a Character is Vowel or Consonant



// Funnction to Find the Largest Number Among Three Numbers
 function bignum(a,b,c){ // Style: space after variables and start of the curly braces
    return (a>b? a>c? a:c :b>c? b:c);
 }
console.log (bignum(1,2,3)) // Style: semicolon missing

//Switch
// You are given a variable, . Your task is to print:
// - ONE, if num is equal to .
// - TWO, if num is equal to .
// - THREE, if num is equal to .
// - FOUR, if num is equal to .
// - FIVE, if num is equal to .
// - SIX, if num is equal to .
// - SEVEN, if num is equal to .
// - EIGHT, if num is equal to .
// - NINE, if num is equal to .
// - PLEASE TRY AGAIN, if  is none of the above.

function number(){
    
}


// You are given a variable marks. Your task is to print:
// - AA if marks is greater than 90.
// - AB if marks is greater than 80 and less than or equal to 90
// - BB if marks is greater than 70 and less than or equal to 80
// - BC if marks is greater than 60 and less than or equal to 70
// - CC if marks is greater than 50 and less than or equal to 60
// - CD if marks is greater than 40 and less than or equal to 50
// - DD if marks is greater than 30 and less than or equal to 40
// - FF if marks is less than or equal to 30




// Funnction to generate Multiplication Table of a given number (use alert for number input)
// function multab(num){
//     prompt(enter number)
// }


// Funnctionn to calculate the Factorial of a Number


// Output: var x = 10 + "1"; console.log(x); typeof x;


//  Solve: 225 % 6 = ?



// Take two numbers and what to do with that number from user.
// Define an object with these function (add, sub, multiply, divide). Perform the operation


// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
